language: python
python:
  - "3.3"
  - "3.4"
install:
  # Build/test dependencies
  - pip install -r requirements.txt -r dev-requirements.txt
script:
  # Normal tests
  - py.test --boxed
  # Integration tests
after_success:
  - coveralls
